version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: campus-platform-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  redis:
    image: redis:7.2-alpine
    container_name: campus-platform-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mongodb_data:
  redis_data:
